package ir.momeni.slyther.common;

import jakarta.persistence.*;
import lombok.Getter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;


/**
 * Base class for entities to standardize primary ID and timestamp fields.
 * <p>
 * All entities extending this class inherit:
 * <ul>
 *     <li>{@code id} — Primary key autogenerated by the database</li>
 *     <li>{@code createdAt} — Timestamp stored once upon insertion</li>
 *     <li>{@code updatedAt} — Automatically updated on every change</li>
 * </ul>
 * <p>
 * This class should NOT be registered as its own table since it uses {@link MappedSuperclass}.
 */
@MappedSuperclass
@Getter
public abstract class BaseEntity {
    /**
     * Primary key generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /**
     * Timestamp of when the entity was created.
     * Automatically set by Hibernate on persist.
     * → Cannot be updated after insertion.
     */
    @CreationTimestamp
    @Column(updatable = false)
    private Instant createdAt;


    /**
     * Timestamp of the last update to the entity.
     * Automatically refreshed on updates.
     */
    @UpdateTimestamp
    private Instant updatedAt;
}
